### PR TITLE
Let users interactively accept or reject SSH host keys

### LINKED ISSUE #465: SSH Tunnel stopped working
ssh-tunnel used to work, 1.1-dev just complains that the remote host is missing from the known-hosts.
I've tried to add a known-hosts-file by running ssh-keyscan into a file and using that file, that does unfortunately not change the behaviour.

If there's anything else I can provide please tell me.

### PR DESCRIPTION
**Pull request by oakkitten**
this removes the “Known hosts” preference.

instead, upon connecting to a previously unseen server, user is presented with an “Unknown server” dialog that displays the key type and the sha256 key fingerprint, and where the user can accept that key and immediately reconnect, or reject it and cancel connecting.

if the key has changed, or if we have a key of a type different to the type of key the server is offering, a warning dialog is show with a single button “Back to safety” and an offer to go to the preferences and clear known hosts using the “Clear known hosts” preference that replaces the “Known hosts” preference.

this required reimplementation of the server key verifier. different to the previous approach,
* all server and port combinations are regarded as separate
* when connecting to a host (example.com), its ip addresses are not considered. for reasons, see comment in SSHServerKeyVerifier.kt
* the keys are not decoded by the verifier because why

also, it's Kotlin now!

closes #465

### CODE REVIEW

**Comment by oakkitten** [comment]
note to self: it is possible to use several ECDSA keys with different curves for host key verification at the same time. these can be generated with e.g.:

	ssh-keygen -q -N "" -t ecdsa -b 521 -f /etc/ssh/ssh_host_ecdsa_521_key

and specified in `/etc/ssh/sshd_config`:

    HostKey /etc/ssh/ssh_host_ecdsa_256_key
    HostKey /etc/ssh/ssh_host_ecdsa_384_key
    HostKey /etc/ssh/ssh_host_ecdsa_521_key

`ssh-keyscan` will not reveal all these keys, but it is still possible to connect using different keys by running e.g.

    ssh user@localhost -oHostKeyAlgorithms=ecdsa-sha2-nistp521

i don't think it's possible to have multiple keys of the same type and curve, however.

**Comment by oakkitten** [comment]
another note: the behavior of `ssh` is a bit surprising. if you have, say, server's rsa key in `~/.ssh/known_hosts`, and try connecting using `ssh user@localhost`, it works. this also works:

    ssh user@localhost -oHostKeyAlgorithms=rsa-sha2-512,ssh-ed25519

but this doesn't work:

    ssh user@localhost -oHostKeyAlgorithms=ssh-ed25519,rsa-sha2-512

also if you put this setting into `ssh_config`, it doesn't work. if you put the default value for this setting from `ssh_config`, it doesn't work either. no idea why

**Comment by minus7** [comment]
This replaces the `ssh_known_hosts` pref with `ssh_server_key_verifier` in the code but leaves the old perf around. Not sure if it makes sense to clean that up.

**Comment by oakkitten** [comment]
do you mean the strings related to the known hosts preference, or something else?

**Comment by minus7** [comment]
I mean the old known hosts data in the shared preferences that older releases will have written there.

**Comment by oakkitten** [comment]
ah, right. yeah we could clean this up

**Comment by oakkitten** [comment]
note to self: see comment in relay's build.gradle

**Comment by oakkitten** [comment]
some thoughts on sshj, since sshj might be able to help us here

well, it does and doesn't. 

first of all, we can use some of sshj's `OpenSSHKnownHosts` instead of `SSHServerKeyVerifier.kt`. it considers ports, also it deems ECDSA keys distinct. we can subclass it to throw appropriate exceptions and also i think it would be possible to add keys.

it doesn't seem like sshj supports `UpdateHostkeys`, or going to support any time soon. `sshlib` has solid plans

if you look at `SSHServerKeyVerifier.kt`, half of the code is serving `getPreferredServerHostKeyAlgorithmsForServer()`, and this part is as of today  non-existent in sshj. it doesn't seem to be doing host key filtering at all. this is not too hard and we can also do it ourselves as we are doing now, but it will involve recreating the config for every connection and frankly this should be fixed in sshj.

ECDSA host keys seem to be broken in sshj. these requires `SecurityUtils.setSecurityProvider("BC")` and it breaks other things (or not?)

the biggest problem is key importing. for various reasons, mostly because of BC, keys can't be imported in a format that is suitable for AKS. DSA keys seem to be not importable at all (who cares about DSA but still). a workaround [here](https://github.com/ubergeek42/weechat-android/commit/ae9f30c1febec9533971e603024e67022b6130ac) only supports PEMs and not the OpenSSH format.

aand sshj is still slightly slower on startup.

**Pull request merged**
