### PR TITLE
Fix emoji rendering on Android 11 and older

### LINKED ISSUE #535: Modern emoji support on "old" Android
Currently, emoji 11.0 and newer (examples: 🦜 🟪 🦤) are rendered as tofu (☐) on my phone running Android 8.

According to https://developer.android.com/guide/topics/ui/look-and-feel/emoji2, fixing this should be as easy as upgrading appcompat to 1.4 (provided the main text view [extends `AppCompatActivity`](https://developer.android.com/guide/topics/ui/look-and-feel/emoji2#appcompat-displays-tofu-not-using-appcompat)).

I tried to do this myself but after bumping the SDK version to 31 (required by appcompat 1.4) I kept getting the following error

```
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```

even after applying the suggested fix.

### PR DESCRIPTION
**Pull request by ncfavier**
Fixes #535, see there for context. For the most part, upgrading `appcompat` to 1.4 was sufficient, except for the main chat view where using `EmojiCompat` directly was necessary, as described [here](https://developer.android.com/guide/topics/ui/look-and-feel/emoji2#no-widgets).

<details>
<summary>Screenshot</summary>

screenshot
</details>

### CODE REVIEW

**Comment by oakkitten** [comment]
I just had this crash in 00419c6, but now can't repro
```
2022-06-14 20:41:14.904 15138-15138/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ubergeek42.WeechatAndroid.debug, PID: 15138
    java.lang.IllegalStateException: Not initialized yet
        at androidx.core.util.Preconditions.checkState(Preconditions.java:169)
        at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:1071)
        at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:1029)
        at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:991)
        at androidx.emoji2.text.EmojiCompat.process(EmojiCompat.java:957)
        at com.ubergeek42.WeechatAndroid.views.AlphaLayout$Companion.make(AlphaLayout.kt:60)
        at com.ubergeek42.WeechatAndroid.views.LineView$wideLayoutDelegate$1.invoke(LineView.kt:108)
        at com.ubergeek42.WeechatAndroid.views.LineView$wideLayoutDelegate$1.invoke(LineView.kt:108)
        at com.ubergeek42.WeechatAndroid.utils.SynchronizedInvalidatableLazyProperty.getValue(Properties.kt:40)
        at com.ubergeek42.WeechatAndroid.views.LineView.getWideLayout(LineView.kt:111)
        at com.ubergeek42.WeechatAndroid.views.LineView.measureViewHeight$getTextOnlyHeight(LineView.kt:190)
        at com.ubergeek42.WeechatAndroid.views.LineView.measureViewHeight(LineView.kt:198)
        at com.ubergeek42.WeechatAndroid.views.LineView.onMeasure(LineView.kt:240)
        at android.view.View.measure(View.java:25466)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9119)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1583)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
```

**Comment by ncfavier** [comment]
Relevant documentation: [EmojiCompat](https://developer.android.com/reference/kotlin/androidx/emoji2/text/EmojiCompat), [EmojiCompatInitializer](https://developer.android.com/reference/kotlin/androidx/emoji2/text/EmojiCompatInitializer). Not sure what changed that makes the default behaviour not enough.

**Comment by oakkitten** [comment]
I can also reproduce it in 53d38ff5. Can you reproduce it on your device? Mine's Android 11/Lineage OS 18.1

**Comment by ncfavier** [comment]
Yes, can reproduce

**Comment by ncfavier** [comment]
Seems like I can also reproduce this on master, in an Android 11 emulator.

An obvious fix would be

```kotlin
val text = try {
    EmojiCompat.get().process(spannable) ?: spannable
} catch (e: IllegalStateException) {
    spannable
}
```

I'm not sure if it's worth delaying this until the EmojiCompat instance is initialised, or how to do it.

**Comment by oakkitten** [comment]
I think it's a previous gradle update? Also this error was reported.

`E Utils   : java.io.InvalidClassException: com.ubergeek42.WeechatAndroid.service.P$BufferHotData; local class incompatible: stream classdesc serialVersionUID = -3081286741800457889, local class serialVersionUID = -2122111488306751778
`

**Pull request merged**
