### PR TITLE
Fix up strings related to input history navigation

### PR DESCRIPTION
**Pull request by oakkitten**
German translations pending

### CODE REVIEW

**Comment by zopieux** [comment]
What's wrong about the plurals?

**Comment by oakkitten** [comment]
Tfw you carefully spell out the reasoning in the commit message but still get asked questions like this 😔

**Comment by zopieux** [comment]
tfw you expect me to do 3 clicks to discover the extended commit message which should have been pasted in the PR description

**Comment by zopieux** [comment]
The whole point of an i18n framework is to deal with language specific shenanigans. Why can't Russian use a single version for all numbers here? Is there a technical limitation from Android?

Note I really couldn't care less about this random plural in a toast absolutely nobody will see in the next 20 years, so lgtm. But the rationale for that change seems bonkers to me.

**Review by zopieux — APPROVED** [review]

**Comment by oakkitten** [comment]
Not sure if I explained this elsewhere or if I should; anyway,

In Russian you usually use different forms of plurals depending on the last digit of the number, e.g. 1 кот 😼, 2/3/4 кота 🐱🐱, 5/6/7/8/9/10/... котов 🐈🐈🐈. It wraps around at 21, and you say 21 кот 😼. Formatting these correctly is what the i18n framework does for you. 

However, if you omit the number, for any unknown plural number you'd use коты, which is distinct from any of the above words and also doesn't wrap in any way... So you have to use something else

**Comment by oakkitten** [comment]
@weechatter Would be nice to have the German translations corrected here as well

Source https://github.com/ubergeek42/weechat-android/blob/1501f874a2e3e2c7b4f6ba32f5cd62e2d76efca1/app/src/main/res/values/strings.xml#L722-L731

Current German translation https://github.com/ubergeek42/weechat-android/blob/1501f874a2e3e2c7b4f6ba32f5cd62e2d76efca1/app/src/main/res/values-de/strings.xml#L706-L709

If you would just write the strings here as a comment and I'll do the rest

**Comment by weechatter** [comment]
Translation is ok for me

**Pull request merged**
