### PR TITLE
Add option to display buffers in hierarchical order

### PR DESCRIPTION
**Pull request by LinusCDE**
This modification allows the buffer sidebar to display hierarchical. The list will be sorted alphabetically by full buffer names and have channels appear as child items (just indented with 5 spaces).

That option can be enabled in "Buffer list" preferences and overrides the "sort buffer list" preference. Ideally this would be in a radio dialog. But I currently didn't have the time for that.
New option

That option doesn't have an french translation.

The after enabling the new option, the buffer list will look like this.
(The order is the same as Glowing-Bear uses.)
Buffer list with option enabled

When filtering, the list will in most cases fall back to alphabetical sort and be flattened again. Though keeping the root items of filtered ones could also be implemented.

There were also some problems compiling the app, which I took care of first.

---

One additonal note would be that **the app crashed** when encountering an "untrusted cert". The F-Droid release gave me a dialog for that, but for me that only worked with the dev build on my machine. Every other build crashed with that message when connecting with WeeChat SSL:
```
2019-10-31 04:32:51.751 6820-6844/? E/🐶: con0 : AbstractConnection connectOnce(): exception while state == CONNECTING
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:355)
        at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:200)
        at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:445)
        at com.ubergeek42.weechat.relay.connection.SSLConnection.doConnect(SSLConnection.java:3)
        at com.ubergeek42.weechat.relay.connection.AbstractConnection.connectOnce(AbstractConnection.java:1)
        at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$100(AbstractConnection.java:1)
        at com.ubergeek42.weechat.relay.connection.AbstractConnection$1.run(AbstractConnection.java:1)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:644)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:493)
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:319)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:113)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:87)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:116)
        at com.ubergeek42.WeechatAndroid.service.SSLHandler$UserTrustManager.checkServerTrusted(SSLHandler.java:4)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:207)
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:592)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
        at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:200) 
        at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:445) 
        at com.ubergeek42.weechat.relay.connection.SSLConnection.doConnect(SSLConnection.java:3) 
        at com.ubergeek42.weechat.relay.connection.AbstractConnection.connectOnce(AbstractConnection.java:1) 
        at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$100(AbstractConnection.java:1) 
        at com.ubergeek42.weechat.relay.connection.AbstractConnection$1.run(AbstractConnection.java:1) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:644) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:493) 
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:319) 
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:113) 
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:87) 
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:116) 
        at com.ubergeek42.WeechatAndroid.service.SSLHandler$UserTrustManager.checkServerTrusted(SSLHandler.java:4) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:207) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:592) 
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351) 
        at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:200) 
        at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:445) 
        at com.ubergeek42.weechat.relay.connection.SSLConnection.doConnect(SSLConnection.java:3) 
        at com.ubergeek42.weechat.relay.connection.AbstractConnection.connectOnce(AbstractConnection.java:1) 
        at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$100(AbstractConnection.java:1) 
        at com.ubergeek42.weechat.relay.connection.AbstractConnection$1.run(AbstractConnection.java:1) 
        at java.lang.Thread.run(Thread.java:764) 
2019-10-31 04:32:51.979 6820-6820/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ubergeek42.WeechatAndroid, PID: 6820
    java.lang.NoSuchFieldError: No static field DIGITS_LOWER of type [C in class Lorg/apache/commons/codec/binary/Hex; or its superclasses (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.ubergeek42.WeechatAndroid.utils.UntrustedCertificateDialog.onCreateDialog(UntrustedCertificateDialog.java:7)
        at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:3)
        at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:83)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:6)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:189)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:24)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:50)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:10)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:4)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6709)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```
The funny thing is, that the cert shouldn't be invalid at all. The cert is from Let's Encrypt and was intended for an HTTPS-Server. I only use it on a non-standard port.

Since I didn't change anything in that area, it isn't probably a result of my changes. Probably some tightened security guidelines on androids side or a more specific build.

### CODE REVIEW

**Comment by oakkitten** [comment]
hello and welcome to our little family of w-a devs!

didn't look at the code yet, a couple of thoughts

1. what's the rationale for this? since the sorting of buffers is normally done in weechat itself—and there are scripts for automating that—is the idea to have two different buffer arrangements in weechat and w-a?

2. the server buffers are currently shown in a different color, so do we need the indentation?

3. make servers collapsible?

4. how does this behave when buffers get highlighted? the current behavior is to push them to the top, so that they are all visible at once. if we are preserving buffer hierarchy, perhaps this behavior could be altered in some way?

5. > When filtering, the list will in most cases fall back to alphabetical sort and be flattened again. Though keeping the root items of filtered ones could also be implemented.

    i personally don't use network-hierarchical ordering, but if i did, i'd probably want networks preserved when filtering—this way if i have channel #foo on network A and channel #foo on network B, i could easily tell them apart. might be useful for people who don't want to renamed similarly-named channel for some reason. this would work for me as i'm only on a few networks, but i'd like to hear more from people who actually use this sorting—perhaps they are on many networks and this wouldn't work well?

P.S. does the crash happen on `connection-refactor-streams` branch?

**Comment by LinusCDE** [comment]
> 1. what's the rationale for this? since the sorting of buffers is normally done in weechat itself—and there are scripts for automating that—is the idea to have two different buffer arrangements in weechat and w-a?

I used weechat to some extend. But I currently don't have time to dive into it fully. I suspected that it would be possible, but didn't try it, yet. I mainly use weechat as my constantly available irc relay/server. And since glowing-bear also sorts the buffers, I found it cool to have that same functionality on my phone.

> 2. the server buffers are currently shown in a different color, so do we need the indentation?

Because glowing-bear does it, too. I just find it nice to have some kind of hierarchy. Even a fake one. Though the colors will work fine, too.

> 3. make servers collapsible?

Would certainly be nice, too. I didn't implement it because the night was already late and that would require a lot more modifications that would probably lead to separating the code more to stay clean. But a "hack" would certainly work for that, too.

4. how does this behave when buffers get highlighted? the current behavior is to push them to the top, so that they are all visible at once. if we are preserving buffer hierarchy, perhaps this behavior could be altered in some way?

The tabs at the top aren't affected by that. The buffer list stays the same. I haven't noticed any oddities on that.

> 5. > When filtering, the list will in most cases fall back to alphabetical sort and be flattened again. Though keeping the root items of filtered ones could also be implemented.

> i personally don't use network-hierarchical ordering, but if i did, i'd probably want networks preserved when filtering—this way if i have channel #foo on network A and channel #foo on network B, i could easily tell them apart. might be useful for people who don't want to renamed similarly-named channel for some reason. this would work for me as i'm only on a few networks, but i'd like to hear more from people who actually use this sorting—perhaps they are on many networks and this wouldn't work well?

That can certainly be added to. I didn't do it since I didn't deem worthy it extending the late night even more. But would be cool indeed.  
It would certainly be useful. You have a good point there.

> P.S. does the crash happen on connection-refactor-streams branch?

I compiled a release on that branch and that worked fine.


On another note. My implementation still has the bug, that it doesn't get sorted again once a buffer gets added. I trigger a full update in BufferListAdapter.java line 144:
```java
    // <snip>
    @AnyThread @Override @Cat("??") synchronized public void onBuffersChanged() {
        // In case that hierarchical order was changed the text needs to be changed.
        Weechat.runOnMainThread(() -> notifyItemRangeChanged(0, getItemCount()));
        // <snip>
    }
    // <snip>
```

The `notifyItemRangeChanged` call should probably get added to that hook as well.  
Currently I need to either kill the app or reconnect to properly sort a new buffer.

**Comment by oakkitten** [comment]
sorry for not getting back to you sooner

i think something like buffer sorting is best left to weechat, e.g. `autosort.py` seems to be a popular script to do exactly this kind of sorting (and more!)

we are also sorting open buffers (in the toolbar) by the buffer numbers now, so if you use a script that will also be consistent.

i am sorry but i don't think that this as such is doing more than the script. something like collapsing servers might be useful although it's hard for me to imagine a case where i would prefer it to filtering. either way, this would warrant a new pr. i'll be closing this, then. sorry about this.

if you are still willing to work on w-a you're more than welcome on our irc channel

**Comment by LinusCDE** [comment]
No problem. I don't really use IRC a lot anyway (sadly). For all my needs the build still does the job and can be seen as just another random fork.
The autosort.py extension sounds interesting. I'll probably look into this at some point in time.

**Pull request closed without merging**
