### PR TITLE
feature/emojisupport

### PR DESCRIPTION
**Pull request by cs8898**
Upgraded to current build tools and introduced an Emojifyer

### CODE REVIEW

**Comment by oakkitten** [comment]
why?

**Comment by cs8898** [comment]
was currently wondering if i should better implenent that directly into weechat, but that was after i created the PR

Its just therefore to replace :the_horns: with 🤘

**Comment by mhoran** [comment]
I'd rather see this in weechat so it works in my terminal than in the client.

**Comment by cs8898** [comment]
At the current moment so do i, but probably the EmojiCompat should be integrated

**Comment by cs8898** [comment]
Found the correct Script :man_facepalming:
https://weechat.org/scripts/source/emoji_aliases.py.html/

**Comment by cs8898** [comment]
No EmojiSupport Lib (Android 4.4)
No EmojiSupport
With EmojiSupport Lib (Android 4.4)
2019-02-13-154739_398x691_scrot

**Comment by oakkitten** [comment]
i'm closing this as it's hella old and we probably don't care enough about android 4 anymore

**Pull request closed without merging**
