### PR TITLE
remove ability to control text size using volume buttons (fixes #173)

### LINKED ISSUE #173: (Optionally) make the volume keys change the volume, not the text size
Some of us don't change the text size all that often!

### PR DESCRIPTION
**Pull request by breunigs**
I'm not an Android dev, so I did my best to update the docs for `notifyOpenBuffersMustBeProcessed`.

### CODE REVIEW

**Comment by mhoran** [comment]
This has come up a few times. I'd prefer a preference, as I do use the volume button feature. Perhaps you could investigate? Happy to give some pointers.

**Comment by breunigs** [comment]
Hm, seems travis failed because gradle hosting is down?

As for the preference: I thought about this while implementing and decided against this. In general, each pref increases code maintenance and the complexity of the settings dialog. It is thus reasonable in my opinion to avoid prefs if there is an obvious default. In other words, is the feature worth having a pref for it? 

I can kinda see that one wants to cram in as much text as possible, given IRC is quite text heavy. Then again, virtually every other app has managed to find a sensible solution that doesn't require constant changing. Mostly I recall of having a normal text size and "big" for the visually impaired.

On top of that, this feature breaks/conflicts with standard Android behaviour and a pref will *not* solve this issue. Basically, people will try this feature, maybe even think it's nice… until they try to skip to the next song or decrease volume and find it is not in line with their expectations. 

So, there are a lot of downsides (complexity, conflict with volume) while only working around the root issue. I'd rather remove this feature entirely and explore less either-or possibilities. For instance, if there is *really* a need to zoom constantly, why not use pinch-to-zoom? No pref required and in line with standard behaviour.

**Comment by mhoran** [comment]
Agreed re: preferences. Perhaps pinch-to-zoom is a better solution, though in other text based apps (aside from Chrome, etc.), I haven't seen this behavior. The volume up/down behavior has been "standard" since early days, specifically on the G1. ConnectBot is the first app I'm aware of which utilized the volume buttons for font size control. Of course, things have changed a lot since then -- but I do find myself utilizing the volume buttons to control font size as my vision changes throughout the day.

I'll defer to @ubergeek42 for the final decision.

**Comment by GLolol** [comment]
I would like to see this as an option too, and not completely removed. I find the volume button resizing quite useful myself.

**Comment by ubergeek42** [comment]
This was fixed by a different pull request. Thanks for the code though!

**Pull request closed without merging**
